package math.general.TermElements;

public enum TermOperatorType {
    TERM_OPERATOR_TYPE_PLUS, TERM_OPERATOR_TYPE_MINUS, TERM_OPERATOR_TYPE_MULTIPLICATION, TERM_OPERATOR_TYPE_DIVISION, TERM_OPERATOR_TYPE_TAN,
    TERM_OPERATOR_TYPE_SIN, TERM_OPERATOR_TYPE_COS, TERM_OPERATOR_TYPE_LOG, TERM_OPERATOR_TYPE_POWER
}
